security:
  oauth2:
    resource:
      user-info-uri: https://graph.windows.net/yourcustomer.onmicrosoft.com/user?api-version=beta
      token-info-uri: https://login.microsoftonline.com/yourcustomer.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=${azure.policy.signin-policy}
      jwt:
        key-uri: https://login.microsoftonline.com/yourcustomer.onmicrosoft.com/discovery/v2.0/keys?p=${azure.policy.signin-policy}

logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true

azure:
  #Custom Values for Azure B2C policies
  policy:
    wellknown-url: https://login.microsoftonline.com/yourcustomer.onmicrosoft.com/v2.0/.well-known/openid-configuration
    signin-policy: yoursigninpolicy
    signup-policy: yoursignUPpolicy
    edit-profile-policy: yourEditProfilepolicy
    meta-data-refresh-cron: 0 5 * * * *
    rsa-keys-refresh-cron: 1 5 * * * *
    verifier-refresh-cron: 2 5 * * * *
  #Client and user authentication configuration
  customer:
    access-token-uri: https://login.microsoftonline.com/yourcustomer.onmicrosoft.com/oauth2/v2.0/token?p=${azure.policy.signin-policy}
    client-id: theAzure_clientId
    client-secret: theAzure_appKey
    pre-established-redirect-uri: https://localhost:8443/login/azure
    response_type: code id_token
    scope: openid
    token-name: id_token
    user-authorization-uri: https://login.microsoftonline.com/yourcustomer.onmicrosoft.com/oauth2/v2.0/authorize?p=${azure.policy.signin-policy}
    authentication-scheme: query
    redirect-url: https://localhost:8443/login/azure
    response_mode: form_post
  client:
    access-token-uri: https://login.microsoftonline.com/yourcustomer.onmicrosoft.com/oauth2/v2.0/token?p=${azure.policy.signin-policy}
    client-id: theAzure_clientId
    client-secret: theAzure_appKey
    pre-established-redirect-uri: https://localhost:8443/login/azure
    response_type: code id_token
    scope: openid
    token-name: id_token
    user-authorization-uri: https://login.microsoftonline.com/yourcustomer.onmicrosoft.com/oauth2/v2.0/authorize?p=${azure.policy.signin-policy}
    user-account-signup-uri: https://login.microsoftonline.com/yourcustomer.onmicrosoft.com/oauth2/v2.0/authorize?p=${azure.policy.signup-policy}
    authentication-scheme: query
    redirect-url: https://localhost:8443/login/azure
    response_mode: form_post
#    grant_type: authorization_code
#    client-athentication-scheme: query
#    state: random_value_with_session_information_encoded