#server:
#  ssl:
#    key-store: D:\ssl_certs\.keystore
#    key-store-password: changeit
#    key-password: changeit



security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

#Note: I'm not sure if all of these values are set properly or not.
# It seems that some values are being ignored.
azure:
  client:
    accessTokenUri: https://login.microsoftonline.com/replacethiswithyourcustomername.onmicrosoft.com/oauth2/v2.0/token?p=B2C_1_b2c_1_sign_in
    authenticationScheme: query
    clientAuthenticationScheme: query
    clientId: ThisShouldBeTheAzure_ApplicationClientId
    clientSecret: ThisShouldBeTheAzure_AppKey
    grant-type: authorization_code
    pre-established-redirect-uri: https://localhost:8443/login/azure
    redirect-url: https://localhost:8443
    response_type: code
    response_mode: form_post
    state: random_value_with_session_information_encoded
    scope: openId offline_access
    tokenName: code
    user-authorization-uri: https://login.microsoftonline.com/replacethiswithyourcustomername.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_b2c_1_sign_in

  resource:
    userInfoUri: https://graph.windows.net/replacethiswithyourcustomername.onmicrosoft.com/users

github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true

